### ISSUE TITLE
crash when toggling `PCM` in sinkwidget's Advanced options

### ISSUE THREAD

**Issue by rindeal** [lxde/pavucontrol-qt#7]
pavucontrol-gtk has the PCM option checked and greyed out, whilst this app unchecked and togglable. Turning it on does nothing, turning it off crashes the app.

full backtrace:
```
#0  0x00007ffff5fad2e7 in raise () from /lib64/libc.so.6                                                                                                                             
No symbol table info available.                                                                                                                                                      
#1  0x00007ffff5fae76a in abort () from /lib64/libc.so.6                                                                                                                             
No symbol table info available.                                                                                                                                                      
#2  0x00007ffff7361bd0 in pa_ext_device_restore_save_formats (c=<optimized out>, type=type@entry=PA_DEVICE_TYPE_SINK,                                                                
    idx=idx@entry=0, n_formats=n_formats@entry=0 '\000', formats=formats@entry=0xb3e150, cb=cb@entry=0x0, userdata=0x0)                                                              
    at /tmp/portage/media-sound/pulseaudio-9.0/work/pulseaudio-9.0/src/pulse/ext-device-restore.c:309                                                                                
        tag = 32767                                                                                                                                                                  
        o = <optimized out>                                                                                                                                                          
        t = <optimized out>                                                                                                                                                          
        __func__ = "pa_ext_device_restore_save_formats"                                                                                                                              
        __PRETTY_FUNCTION__ = "pa_ext_device_restore_save_formats"                                                                                                                   
#3  0x000000000041f4ba in SinkWidget::onEncodingsChange (this=0x98d2f0)                                                                                                              
    at /tmp/portage/media-sound/pavucontrol-qt-9999/work/pavucontrol-qt-9999/src/sinkwidget.cc:186                                                                                   
        o = <optimized out>                                                                                                                                                          
        n_formats = 0 '\000'                                                                                                                                                         
        formats = 0xb3e150                                                                                                                                                           
#4  0x000000000041f6d7 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (SinkWidget::*)()>::call(voi                                                d (SinkWidget::*)(), SinkWidget*, void**) (arg=<optimized out>, o=<optimized out>, f=<optimized out>)                                                                                
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:501                                                                                
No locals.                                                                                                                           
#5  QtPrivate::FunctionPointer<void (SinkWidget::*)()>::call<QtPrivate::List<>, void>(void (SinkWidget::*)(), SinkWidget*, void**) ( 
    arg=<optimized out>, o=<optimized out>, f=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:520                     
No locals.                                                                                                                           
#6  QtPrivate::QSlotObject<void (SinkWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>)                    
    at /usr/include/qt5/QtCore/qobject_impl.h:143                                                                                    
No locals.                                                                                                                           
#7  0x00007ffff695e0de in QtPrivate::QSlotObjectBase::call (a=0x7fffffffcf30, r=0x98d2f0, this=<optimized out>)                      
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124                                                              
No locals.                                                                                                                           
#8  QMetaObject::activate (sender=sender@entry=0x99e450, signalOffset=<optimized out>,                                               
    local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffcf30) at kernel/qobject.cpp:3715                        
        obj = {d = 0x9aac60}                                                                                                         
        receiverInSameThread = <optimized out>                                                                                       
        sw = {receiver = 0x98d2f0, previousSender = 0x0, currentSender = {sender = 0x99e450, signal = 11, ref = 1}, switched = true} 
        callFunction = 0x9aac60                                                                                                      
        receiver = 0x98d2f0                                                                                                          
        method_relative = <optimized out>
        c = 0x9aac90
        last = 0x9aac90
        locker = {val = 140737332587080}
        connectionLists = {connectionLists = 0x9a5b60}
        list = <optimized out>
        signal_index = 11
        empty_argv = {0x0}
        currentThreadId = 0x7ffff7fad840
#9  0x00007ffff695e657 in QMetaObject::activate (sender=sender@entry=0x99e450, 
    m=m@entry=0x7ffff7db3c60 <QAbstractButton::staticMetaObject>, local_signal_index=local_signal_index@entry=4, 
    argv=argv@entry=0x7fffffffcf30) at kernel/qobject.cpp:3595
No locals.
#10 0x00007ffff79d5d32 in QAbstractButton::toggled (this=this@entry=0x99e450, _t1=_t1@entry=false)
    at .moc/moc_qabstractbutton.cpp:314
        _a = {0x0, 0x7fffffffcf2c}
#11 0x00007ffff79d60e5 in QAbstractButtonPrivate::emitToggled (this=this@entry=0x99e490, checked=checked@entry=false)
    at widgets/qabstractbutton.cpp:446
No locals.
#12 0x00007ffff79d7d3c in QAbstractButton::setChecked (this=this@entry=0x99e450, checked=<optimized out>)
    at widgets/qabstractbutton.cpp:639
        s = {disabled = 0, selected = 0, focusable = 0, focused = 0, pressed = 1, checkable = 0, checked = 1, checkStateMixed = 0, 
          readOnly = 0, hotTracked = 0, defaultButton = 1, expanded = 0, collapsed = 0, busy = 1, expandable = 1, marqueed = 1, 
          animated = 1, invisible = 0, offscreen = 0, sizeable = 1, movable = 1, selfVoicing = 0, selectable = 0, linked = 1, 
          traversed = 0, multiSelectable = 0, extSelectable = 0, passwordEdit = 0, hasPopup = 0, modal = 0, active = 0, 
          invalid = 0, editable = 0, multiLine = 0, selectableText = 0, supportsAutoCompletion = 0, searchEdit = 0}
        event = {<QAccessibleEvent> = {_vptr.QAccessibleEvent = 0x99e450, m_type = 4294954960, m_object = 0x640be0, {
              m_child = -11840, m_uniqueId = 4294955456}}, m_changedStates = {disabled = 0, selected = 0, focusable = 0, 
            focused = 0, pressed = 1, checkable = 0, checked = 1, checkStateMixed = 0, readOnly = 0, hotTracked = 0, 
            defaultButton = 1, expanded = 0, collapsed = 0, busy = 1, expandable = 1, marqueed = 1, animated = 1, invisible = 0, 
            offscreen = 0, sizeable = 1, movable = 1, selfVoicing = 0, selectable = 0, linked = 1, traversed = 0, 
            multiSelectable = 0, extSelectable = 0, passwordEdit = 0, hasPopup = 0, modal = 0, active = 0, invalid = 0, 
            editable = 0, multiLine = 0, selectableText = 0, supportsAutoCompletion = 0, searchEdit = 0}}
#13 0x00007ffff79d8347 in QAbstractButton::nextCheckState (this=this@entry=0x99e450) at widgets/qabstractbutton.cpp:899
        this = 0x99e450
#14 0x00007ffff79eab66 in QCheckBox::nextCheckState (this=0x99e450) at widgets/qcheckbox.cpp:367
No locals.
#15 0x00007ffff79d78c0 in QAbstractButtonPrivate::click (this=this@entry=0x99e490) at widgets/qabstractbutton.cpp:386
        changeState = <optimized out>
#16 0x00007ffff79d79cc in QAbstractButton::mouseReleaseEvent (this=0x99e450, e=0x7fffffffd420) at widgets/qabstractbutton.cpp:1002
No locals.
#17 0x00007ffff793dcd8 in QWidget::event (this=0x99e450, event=0x7fffffffd420) at kernel/qwidget.cpp:9114
No locals.
#18 0x00007ffff78fb7dc in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x99e450, e=0x7fffffffd420)
    at kernel/qapplication.cpp:3804
        consumed = <optimized out>
        this = <optimized out>
        e = 0x7fffffffd420
        receiver = 0x99e450
#19 0x00007ffff79011ce in QApplication::notify (this=<optimized out>, receiver=0x99e450, e=0x7fffffffd420)
    at kernel/qapplication.cpp:3277
        me = {<QInputEvent> = {<QEvent> = {_vptr.QEvent = 0x7ffff7032018 <vtable for QMouseEvent+16>, static staticMetaObject = {
                d = {superdata = 0x0, stringdata = 0x7ffff6aed200 <qt_meta_stringdata_QEvent>, 
                  data = 0x7ffff6aecc60 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
              d = 0x0, t = 3, posted = 0, spont = 1, m_accept = 1, reserved = 8191}, modState = {i = 0}, ts = 41928309}, l = {
            xp = 13, yp = 8}, w = {xp = 59, yp = 267}, s = {xp = 626, yp = 478}, b = Qt::LeftButton, mouseState = {i = 0}, 
          caps = 0, velocity = {xp = 0, yp = 0}}
        w = 0x99e450
        mouse = 0x7fffffffd420
        eventAccepted = <optimized out>
        relpos = {xp = 13, yp = 8}
        pw = {wp = {d = 0x9a59a0, value = 0x99e450}}
        res = false
#20 0x00007ffff693811a in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x99e450, event=event@entry=0x7fffffffd420)
    at kernel/qcoreapplication.cpp:1015
        selfRequired = true
        result = false
        cbdata = {0x99e450, 0x7fffffffd420, 0x7fffffffd28f}
        d = <optimized out>
        threadData = 0x645f00
        loopLevelCounter = {threadData = 0x645f00}
#21 0x00007ffff78fff35 in QCoreApplication::sendEvent (event=<optimized out>, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:225
No locals.
#22 QApplicationPrivate::sendMouseEvent (receiver=receiver@entry=0x99e450, event=event@entry=0x7fffffffd420, 
    alienWidget=alienWidget@entry=0x99e450, nativeWidget=0x6bf970, buttonDown=buttonDown@entry=0x7ffff7ddaa90 <qt_button_down>, 
    lastMouseReceiver=..., spontaneous=true) at kernel/qapplication.cpp:2775
        receiverGuard = {wp = {d = 0x9a59a0, value = 0x99e450}}
        nativeGuard = {wp = {d = 0x7abfa0, value = 0x6bf970}}
        alienGuard = {wp = {d = 0x9a59a0, value = 0x99e450}}
        activePopupWidget = {wp = {d = 0x0, value = 0x0}}
        widgetUnderMouse = <optimized out>
        wasLeaveAfterRelease = true
        result = <optimized out>
#23 0x00007ffff79579c0 in QWidgetWindow::handleMouseEvent (this=this@entry=0x7acd10, event=event@entry=0x7fffffffd820)
    at kernel/qwidgetwindow.cpp:603
        translated = {<QInputEvent> = {<QEvent> = {_vptr.QEvent = 0x7ffff7032018 <vtable for QMouseEvent+16>, 
              static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff6aed200 <qt_meta_stringdata_QEvent>, 
                  data = 0x7ffff6aecc60 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
              d = 0x0, t = 3, posted = 0, spont = 1, m_accept = 1, reserved = 12}, modState = {i = 0}, ts = 41928309}, l = {
            xp = 13, yp = 8}, w = {xp = 59, yp = 267}, s = {xp = 626, yp = 478}, b = Qt::LeftButton, mouseState = {i = 0}, 
          caps = 0, velocity = {xp = 0, yp = 0}}
        contextMenuTrigger = QEvent::MouseButtonPress
        widget = 0x99e450
        mapped = {xp = 13, yp = 8}
        receiver = 0x99e450
#24 0x00007ffff795a1fb in QWidgetWindow::event (this=0x7acd10, event=0x7fffffffd820) at kernel/qwidgetwindow.cpp:233
No locals.
#25 0x00007ffff78fb7dc in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x7acd10, e=0x7fffffffd820)
    at kernel/qapplication.cpp:3804
        consumed = <optimized out>
        this = <optimized out>
        e = 0x7fffffffd820
        receiver = 0x7acd10
#26 0x00007ffff7900956 in QApplication::notify (this=0x7fffffffdc90, receiver=0x7acd10, e=0x7fffffffd820)
    at kernel/qapplication.cpp:3561
        w = 0x7acd10
        extra = <optimized out>
        isProxyWidget = <optimized out>
        res = false
#27 0x00007ffff693811a in QCoreApplication::notifyInternal2 (receiver=receiver@entry=0x7acd10, event=event@entry=0x7fffffffd820)
    at kernel/qcoreapplication.cpp:1015
        selfRequired = true
        result = false
        cbdata = {0x7acd10, 0x7fffffffd820, 0x7fffffffd6df}
        d = <optimized out>
        threadData = 0x645f00
        loopLevelCounter = {threadData = 0x645f00}
#28 0x00007ffff6c6ae23 in QCoreApplication::sendSpontaneousEvent (event=0x7fffffffd820, receiver=0x7acd10)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:228
No locals.
#29 QGuiApplicationPrivate::processMouseEvent (e=0xb5f140) at kernel/qguiapplication.cpp:1877
        type = QEvent::MouseButtonRelease
        stateChange = <optimized out>
        window = 0x7acd10
        localPoint = {xp = 59, yp = 267}
        globalPoint = {xp = 626, yp = 478}
        button = Qt::LeftButton
        doubleClick = false
        frameStrut = false
        ev = {<QInputEvent> = {<QEvent> = {_vptr.QEvent = 0x7ffff7032018 <vtable for QMouseEvent+16>, static staticMetaObject = {
                d = {superdata = 0x0, stringdata = 0x7ffff6aed200 <qt_meta_stringdata_QEvent>, 
                  data = 0x7ffff6aecc60 <qt_meta_data_QEvent>, static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}, 
              d = 0x0, t = 3, posted = 0, spont = 1, m_accept = 1, reserved = 7856}, modState = {i = 0}, ts = 41928309}, l = {
            xp = 59, yp = 267}, w = {xp = 59, yp = 267}, s = {xp = 626, yp = 478}, b = Qt::LeftButton, mouseState = {i = 0}, 
          caps = 0, velocity = {xp = 0, yp = 0}}
#30 0x00007ffff6c6c825 in QGuiApplicationPrivate::processWindowSystemEvent (e=e@entry=0xb5f140) at kernel/qguiapplication.cpp:1661
No locals.
#31 0x00007ffff6c4eaeb in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:648
        event = 0xb5f140
        nevents = 1
#32 0x00007fffebf99c00 in userEventSourceDispatch (source=<optimized out>) at eventdispatchers/qeventdispatcher_glib.cpp:70
        userEventSource = <optimized out>
        dispatcher = <optimized out>
#33 0x00007ffff708f0c5 in g_main_dispatch () at /tmp/portage/dev-libs/glib-2.48.1-r1/work/glib-2.48.1/glib/gmain.c:3154
No locals.
#34 g_main_context_dispatch () at /tmp/portage/dev-libs/glib-2.48.1-r1/work/glib-2.48.1/glib/gmain.c:3769
No locals.
#35 0x00007ffff708f281 in g_main_context_iterate () at /tmp/portage/dev-libs/glib-2.48.1-r1/work/glib-2.48.1/glib/gmain.c:3840
No locals.
#36 0x00007ffff708f324 in g_main_context_iteration () at /tmp/portage/dev-libs/glib-2.48.1-r1/work/glib-2.48.1/glib/gmain.c:3901
No locals.
#37 0x00007ffff69838bf in QEventDispatcherGlib::processEvents (this=0x691f10, flags=...) at kernel/qeventdispatcher_glib.cpp:417
        d = 0x694ca0
        canWait = true
        savedFlags = {i = 0}
        result = <optimized out>
#38 0x00007ffff693709a in QEventLoop::exec (this=this@entry=0x7fffffffdba0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
        d = 0x6f1a40
        locker = {val = 6578160}
        ref = {d = 0x6f1a40, locker = @0x7fffffffdb30, exceptionCaught = true}
#39 0x00007ffff693e68d in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1285
        threadData = 0x645f00
        eventLoop = {<QObject> = {_vptr.QObject = 0x7ffff6b6a438 <vtable for QEventLoop+16>, static staticMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6a8e2e0 <qt_meta_stringdata_QObject>, 
                data = 0x7ffff6a8e1c0 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff69655d0 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x6f1a40}, static staticQtMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6ad5de0 <qt_meta_stringdata_Qt>, data = 0x7ffff6ad3360 <qt_meta_data_Qt>, 
                static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff6b6c400 <QObject::staticMetaObject>, stringdata = 0x7ffff6aec860 <qt_meta_stringdata_QEventLoop>, 
              data = 0x7ffff6aec800 <qt_meta_data_QEventLoop>, 
              static_metacall = 0x7ffff69caa90 <QEventLoop::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        returnCode = <optimized out>
#40 0x00007ffff6c6283c in QGuiApplication::exec () at kernel/qguiapplication.cpp:1607
No locals.
#41 0x00007ffff78f8a35 in QApplication::exec () at kernel/qapplication.cpp:2979
No locals.
#42 0x000000000040f3e9 in main (argc=1, argv=<optimized out>)
    at /tmp/portage/media-sound/pavucontrol-qt-9999/work/pavucontrol-qt-9999/src/pavucontrol.cc:693
        app = {<QGuiApplication> = {<QCoreApplication> = {<QObject> = {_vptr.QObject = 0x7ffff7daf828 <vtable for QApplication+16>, 
                static staticMetaObject = {d = {superdata = 0x0, stringdata = 0x7ffff6a8e2e0 <qt_meta_stringdata_QObject>, 
                    data = 0x7ffff6a8e1c0 <qt_meta_data_QObject>, 
                    static_metacall = 0x7ffff69655d0 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                    relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x645d90}, static staticQtMetaObject = {d = {
                    superdata = 0x0, stringdata = 0x7ffff6ad5de0 <qt_meta_stringdata_Qt>, data = 0x7ffff6ad3360 <qt_meta_data_Qt>, 
                    static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
                  superdata = 0x7ffff6b6c400 <QObject::staticMetaObject>, 
                  stringdata = 0x7ffff6aeca20 <qt_meta_stringdata_QCoreApplication>, 
                  data = 0x7ffff6aec900 <qt_meta_data_QCoreApplication>, 
                  static_metacall = 0x7ffff69cac10 <QCoreApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static self = 0x7fffffffdc90}, static staticMetaObject = {d = {
                superdata = 0x7ffff6b6a580 <QCoreApplication::staticMetaObject>, 
                stringdata = 0x7ffff6f820e0 <qt_meta_stringdata_QGuiApplication>, 
                data = 0x7ffff6f81ea0 <qt_meta_data_QGuiApplication>, 
                static_metacall = 0x7ffff6c6ca10 <QGuiApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff7031940 <QGuiApplication::staticMetaObject>, 
              stringdata = 0x7ffff7c61860 <qt_meta_stringdata_QApplication>, data = 0x7ffff7c616e0 <qt_meta_data_QApplication>, 
              static_metacall = 0x7ffff78fe3e0 <QApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        locale = {static null = {<No data fields>}, d = 0x6acaa0}
        qtTranslator = {<QObject> = {_vptr.QObject = 0x7ffff6b6a838 <vtable for QTranslator+16>, static staticMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6a8e2e0 <qt_meta_stringdata_QObject>, 
                data = 0x7ffff6a8e1c0 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff69655d0 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x6b24d0}, static staticQtMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6ad5de0 <qt_meta_stringdata_Qt>, data = 0x7ffff6ad3360 <qt_meta_data_Qt>, 
                static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff6b6c400 <QObject::staticMetaObject>, stringdata = 0x7ffff6aef100 <qt_meta_stringdata_QTranslator>, 
              data = 0x7ffff6aef0c0 <qt_meta_data_QTranslator>, 
              static_metacall = 0x7ffff69cb4d0 <QTranslator::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        appTranslator = {<QObject> = {_vptr.QObject = 0x7ffff6b6a838 <vtable for QTranslator+16>, static staticMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6a8e2e0 <qt_meta_stringdata_QObject>, 
                data = 0x7ffff6a8e1c0 <qt_meta_data_QObject>, 
                static_metacall = 0x7ffff69655d0 <QObject::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
                relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = {d = 0x6b8c60}, static staticQtMetaObject = {d = {
                superdata = 0x0, stringdata = 0x7ffff6ad5de0 <qt_meta_stringdata_Qt>, data = 0x7ffff6ad3360 <qt_meta_data_Qt>, 
                static_metacall = 0x0, relatedMetaObjects = 0x0, extradata = 0x0}}}, static staticMetaObject = {d = {
              superdata = 0x7ffff6b6c400 <QObject::staticMetaObject>, stringdata = 0x7ffff6aef100 <qt_meta_stringdata_QTranslator>, 
              data = 0x7ffff6aef0c0 <qt_meta_data_QTranslator>, 
              static_metacall = 0x7ffff69cb4d0 <QTranslator::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, 
              relatedMetaObjects = 0x0, extradata = 0x0}}}
        parser = {d = 0x691110}
        tabOption = {d = {d = 0x6abb30}}
        retryOption = {d = {d = 0x6b1d50}}
        maximizeOption = {d = {d = 0x6ad010}}
        mainWindow = 0x6bf970
        m = 0x7a2040
        __PRETTY_FUNCTION__ = "int main(int, char**)"
```

**Comment by palinek** [comment]
@rindeal please, confirm the fix.

**Comment by rindeal** [comment]
yep, appears to behave the same as *-gtk now
